# fly.toml app configuration file generated for passry-api on 2025-07-29T05:29:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'passry-api'
primary_region = 'lhr'

[deploy]
  release_command = "pnpm run db:generate; pnpm run db:migrate"

[http_service]
  internal_port = 9999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
