# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
      - staging

env:
  NODE_ENV: staging
  PORT: 9999
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - run: pnpm run deploy:api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
